/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * server_wizard.java
 *
 * Created on Sep 24, 2010, 8:48:58 PM
 */

package wizards;

import server.core.frame.core_main_temp;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import org.xml.sax.SAXException;
import server.FileOperations.XML;
import server.FileOperations.encrypt_and_decrypt;
import static java.lang.Character.isLetter;

/**
 *
 * @author saif
 */



public class server_wizard extends javax.swing.JFrame {

    /* A little hack -o - rama to disappear the main frame
     *
     */

    

    /** Creates new form server_wizard */
    public server_wizard() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jFrame4 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jFrame5 = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jFrame6 = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jFrame7 = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jButton11 = new javax.swing.JButton();
        jFrame8 = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jFrame1.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));
        jPanel2.setMinimumSize(new java.awt.Dimension(710, 460));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel10.setText("Welcome to Radiology Technology's file transfer wizard");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 40, 450, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/rack-server.jpg"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(470, 0, 250, 330);

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel12.setText("Step 2 of 9");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(490, 410, 180, 30);

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel13.setText("Welcome admin !");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 80, 190, 30);

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel14.setText("Your desired username :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 210, 220, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(20, 260, 210, 30);

        jLabel15.setText("Please type your desired username.");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 110, 310, 30);

        jLabel16.setText("This will be needed when you will login into ");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 130, 340, 30);

        jLabel17.setText("your account . ");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(20, 150, 250, 30);

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(20, 310, 100, 40);

        jFrame1.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame2.setMinimumSize(new java.awt.Dimension(700, 500));
        jFrame2.getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(252, 252, 252));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel5.setText("Welcome to Radiology Technology's file transfer wizard");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 40, 450, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/rack-server.jpg"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(540, 0, 160, 400);

        jLabel18.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel18.setText("Step 3 of 9 ");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(490, 410, 180, 30);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel7.setText("Welcome admin !");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 80, 190, 30);

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel8.setText("Your desired password :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 230, 220, 20);

        jLabel19.setText("Set your password. It is advised to store the ");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(20, 120, 380, 20);

        jLabel20.setForeground(java.awt.Color.red);
        jLabel20.setText("password in a secure place. Dont loose it !");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(20, 160, 370, 20);

        jLabel21.setForeground(java.awt.Color.red);
        jLabel21.setText("Warning : Easy password is a easy way to breach");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(20, 140, 410, 30);

        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(20, 390, 100, 40);

        jLabel22.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel22.setText("Type the password again :");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(20, 310, 190, 20);

        jLabel23.setForeground(java.awt.Color.red);
        jLabel23.setText("be 6 characters long.");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(20, 210, 430, 13);

        jLabel24.setForeground(java.awt.Color.red);
        jLabel24.setText("In your password, a character ( a, b etc ) is ");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(20, 180, 380, 13);
        jPanel3.add(jPasswordField1);
        jPasswordField1.setBounds(20, 260, 220, 30);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField2);
        jPasswordField2.setBounds(20, 340, 220, 30);

        jLabel25.setForeground(java.awt.Color.red);
        jLabel25.setText("needed for security, also your password must ");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(20, 190, 340, 20);

        jFrame2.getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 730, 460);

        jFrame3.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame3.setMinimumSize(new java.awt.Dimension(700, 500));
        jFrame3.getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(252, 252, 252));
        jPanel4.setLayout(null);

        jLabel26.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel26.setText("Welcome to Radiology Technology's file transfer wizard");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(20, 40, 450, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/rack-server.jpg"))); // NOI18N
        jPanel4.add(jLabel27);
        jLabel27.setBounds(550, 0, 160, 400);

        jLabel28.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel28.setText("Step 4 of 9");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(490, 410, 180, 30);

        jLabel29.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel29.setText("Set password recovery");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(20, 80, 190, 30);

        jLabel30.setText("A password option will enable you to recover your");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(20, 110, 370, 30);

        jLabel31.setText("account when you have accidentally lost your ");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(20, 130, 350, 30);

        jLabel32.setText("password. You need to set your birthday and a");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(20, 150, 360, 30);

        jLabel33.setText("secret question to set/recover password.");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(20, 180, 350, 13);

        jLabel34.setText("Warning : If you dont set your secret question ");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(20, 220, 380, 13);

        jLabel35.setText("carefully, it can be leak to the security. So it is ");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(20, 240, 390, 13);

        jLabel36.setText("advised to keep your username and password");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(20, 260, 370, 13);

        jLabel37.setText("in a secure place and not to use this option");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(20, 280, 380, 13);

        jButton5.setText("Next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(20, 340, 130, 40);

        jFrame3.getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 710, 460);

        jFrame4.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame4.setMinimumSize(new java.awt.Dimension(700, 500));
        jFrame4.getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(252, 252, 252));
        jPanel5.setLayout(null);

        jLabel38.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel38.setText("Welcome to Radiology Technology's file transfer wizard");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(20, 40, 450, 30);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/rack-server.jpg"))); // NOI18N
        jPanel5.add(jLabel39);
        jLabel39.setBounds(530, 0, 180, 410);

        jLabel40.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel40.setText("Step 5 of 9");
        jPanel5.add(jLabel40);
        jLabel40.setBounds(490, 410, 180, 30);

        jLabel41.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel41.setText("Set password recovery");
        jPanel5.add(jLabel41);
        jLabel41.setBounds(20, 80, 190, 30);

        jLabel42.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel42.setText("Your birthday :");
        jPanel5.add(jLabel42);
        jLabel42.setBounds(20, 200, 220, 20);

        jLabel43.setText("Set your birthday first. Then , set a secret ");
        jPanel5.add(jLabel43);
        jLabel43.setBounds(20, 110, 320, 20);

        jLabel44.setText("question and input the answer.Please remember ");
        jPanel5.add(jLabel44);
        jLabel44.setBounds(20, 130, 360, 20);

        jLabel45.setText("them.");
        jPanel5.add(jLabel45);
        jLabel45.setBounds(20, 150, 320, 20);

        jButton7.setText("Next");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(20, 300, 140, 40);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1);
        jComboBox1.setBounds(20, 230, 70, 23);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(110, 230, 70, 23);
        jPanel5.add(jTextField2);
        jTextField2.setBounds(200, 230, 60, 23);

        jLabel46.setText("Date");
        jPanel5.add(jLabel46);
        jLabel46.setBounds(30, 270, 70, 10);

        jLabel47.setText("Month");
        jPanel5.add(jLabel47);
        jLabel47.setBounds(120, 270, 90, 10);

        jLabel48.setText("Year");
        jPanel5.add(jLabel48);
        jLabel48.setBounds(210, 270, 70, 10);

        jFrame4.getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 710, 460);

        jFrame5.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame5.setMinimumSize(new java.awt.Dimension(700, 500));
        jFrame5.getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(252, 252, 252));
        jPanel6.setLayout(null);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/rack-server.jpg"))); // NOI18N
        jPanel6.add(jLabel49);
        jLabel49.setBounds(540, 0, 170, 390);

        jLabel50.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel50.setText("Welcome to Radiology Technology's file transfer wizard");
        jPanel6.add(jLabel50);
        jLabel50.setBounds(20, 40, 450, 30);

        jLabel51.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel51.setText("Step 6 of 9");
        jPanel6.add(jLabel51);
        jLabel51.setBounds(490, 410, 180, 30);

        jLabel52.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel52.setText("Set password recovery");
        jPanel6.add(jLabel52);
        jLabel52.setBounds(20, 80, 190, 30);

        jLabel53.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel53.setText("Your secret answer :");
        jPanel6.add(jLabel53);
        jLabel53.setBounds(20, 290, 370, 20);

        jLabel54.setText("Set your birthday first. Then , set a secret ");
        jPanel6.add(jLabel54);
        jLabel54.setBounds(20, 110, 410, 20);

        jLabel55.setText("question and input the answer.Please remember ");
        jPanel6.add(jLabel55);
        jLabel55.setBounds(20, 130, 450, 20);

        jLabel56.setText("them.");
        jPanel6.add(jLabel56);
        jLabel56.setBounds(20, 150, 410, 20);
        jPanel6.add(jTextField3);
        jTextField3.setBounds(20, 230, 280, 40);

        jLabel57.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel57.setText("Your secret question :");
        jPanel6.add(jLabel57);
        jLabel57.setBounds(20, 200, 370, 20);
        jPanel6.add(jTextField4);
        jTextField4.setBounds(20, 330, 280, 40);

        jButton8.setText("Set recovery option");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);
        jButton8.setBounds(20, 390, 250, 50);

        jFrame5.getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 710, 460);

        jFrame6.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame6.setMinimumSize(new java.awt.Dimension(700, 500));
        jFrame6.getContentPane().setLayout(null);

        jPanel7.setBackground(new java.awt.Color(252, 252, 252));
        jPanel7.setLayout(null);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/rack-server.jpg"))); // NOI18N
        jPanel7.add(jLabel58);
        jLabel58.setBounds(540, 0, 170, 400);

        jLabel59.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel59.setText("Welcome to Radiology Technology's file transfer wizard");
        jPanel7.add(jLabel59);
        jLabel59.setBounds(20, 40, 450, 30);

        jLabel60.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel60.setText("Step 7 of 9");
        jPanel7.add(jLabel60);
        jLabel60.setBounds(490, 410, 180, 30);

        jLabel61.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel61.setText("Set User priviledges");
        jPanel7.add(jLabel61);
        jLabel61.setBounds(20, 80, 320, 30);

        jLabel62.setText("In this step, you can set user account priviledges. Users");
        jPanel7.add(jLabel62);
        jLabel62.setBounds(20, 110, 400, 20);

        jLabel63.setText("can access to this application according to the ");
        jPanel7.add(jLabel63);
        jLabel63.setBounds(20, 130, 420, 20);

        jLabel64.setText("priviledge you set.");
        jPanel7.add(jLabel64);
        jLabel64.setBounds(20, 150, 380, 20);

        jButton6.setText("Next");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);
        jButton6.setBounds(20, 230, 130, 40);

        jFrame6.getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 0, 710, 460);

        jFrame7.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame7.setMinimumSize(new java.awt.Dimension(700, 500));
        jFrame7.getContentPane().setLayout(null);

        jPanel8.setBackground(new java.awt.Color(252, 252, 252));
        jPanel8.setLayout(null);

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/rack-server.jpg"))); // NOI18N
        jPanel8.add(jLabel65);
        jLabel65.setBounds(540, 0, 170, 400);

        jLabel66.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel66.setText("Welcome to Radiology Technology's file transfer wizard");
        jPanel8.add(jLabel66);
        jLabel66.setBounds(20, 40, 450, 30);

        jLabel67.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel67.setText("Step 8 of 9");
        jPanel8.add(jLabel67);
        jLabel67.setBounds(490, 410, 180, 30);

        jLabel68.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel68.setText("Set User priviledges");
        jPanel8.add(jLabel68);
        jLabel68.setBounds(20, 80, 320, 30);

        jLabel69.setText("Please set user priviledges according to your need.");
        jPanel8.add(jLabel69);
        jLabel69.setBounds(20, 110, 400, 20);

        jCheckBox1.setText("Users can add clients");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel8.add(jCheckBox1);
        jCheckBox1.setBounds(70, 160, 250, 20);

        jCheckBox2.setText("Users can edit/delete client options");
        jPanel8.add(jCheckBox2);
        jCheckBox2.setBounds(70, 190, 300, 20);

        jCheckBox3.setText("Users can chat with clients");
        jPanel8.add(jCheckBox3);
        jCheckBox3.setBounds(70, 220, 250, 20);

        jCheckBox4.setText("Users can see logs");
        jPanel8.add(jCheckBox4);
        jCheckBox4.setBounds(70, 280, 280, 20);

        jCheckBox5.setText("Users can send messages.");
        jPanel8.add(jCheckBox5);
        jCheckBox5.setBounds(70, 250, 270, 20);

        jCheckBox6.setText("Users can add/remove files");
        jPanel8.add(jCheckBox6);
        jCheckBox6.setBounds(70, 310, 360, 20);

        jCheckBox7.setText("User can set file profiles for clients");
        jPanel8.add(jCheckBox7);
        jCheckBox7.setBounds(70, 340, 320, 20);

        jCheckBox8.setText("Users can change settings");
        jPanel8.add(jCheckBox8);
        jCheckBox8.setBounds(70, 370, 320, 20);

        jButton11.setText("Next");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11);
        jButton11.setBounds(200, 410, 110, 40);

        jFrame7.getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 0, 710, 460);

        jFrame8.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame8.setMinimumSize(new java.awt.Dimension(700, 500));
        jFrame8.getContentPane().setLayout(null);

        jPanel9.setBackground(new java.awt.Color(252, 252, 252));
        jPanel9.setLayout(null);

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/rack-server.jpg"))); // NOI18N
        jPanel9.add(jLabel70);
        jLabel70.setBounds(540, 0, 170, 400);

        jLabel71.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel71.setText("Finished !");
        jPanel9.add(jLabel71);
        jLabel71.setBounds(20, 40, 450, 30);

        jLabel72.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel72.setText("Step 9 of 9 ");
        jPanel9.add(jLabel72);
        jLabel72.setBounds(490, 410, 180, 30);

        jLabel73.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel73.setText("You have successfully finished the wizard !");
        jPanel9.add(jLabel73);
        jLabel73.setBounds(20, 80, 320, 30);

        jLabel74.setText("The software has gather enough data for the first run.");
        jPanel9.add(jLabel74);
        jLabel74.setBounds(20, 110, 420, 20);

        jLabel75.setText("If you want a quick overview of the software's features,");
        jPanel9.add(jLabel75);
        jLabel75.setBounds(20, 130, 420, 20);

        jLabel76.setText("click \"no, i will see it later on\".");
        jPanel9.add(jLabel76);
        jLabel76.setBounds(20, 170, 380, 20);

        jLabel77.setText("please select, \"i want to see the demo\". Otherwise, ");
        jPanel9.add(jLabel77);
        jLabel77.setBounds(20, 150, 380, 20);

        jButton12.setText("I want to see the demo");
        jPanel9.add(jButton12);
        jButton12.setBounds(30, 220, 350, 50);

        jButton13.setText("No, i will see it later on.");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton13);
        jButton13.setBounds(30, 300, 350, 50);

        jFrame8.getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 0, 710, 460);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel2.setText("Welcome to Radiology Technology's file transfer wizard");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 450, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/rack-server.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(470, 0, 230, 330);

        jButton1.setText("Start the wizard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 200, 250, 40);

        jButton2.setText("Exit");
        jPanel1.add(jButton2);
        jButton2.setBounds(50, 270, 250, 40);

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel9.setText("Step 1 of ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(490, 410, 180, 30);

        jLabel3.setText("the application easily.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 120, 270, 20);

        jLabel4.setText("Please select \"Start the wizard\" to set up the ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 100, 270, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        setVisible(false);
        jFrame1.setBounds(100, 100, 710, 500);
    jFrame1.setVisible(true);

    /* adding dates in the jFrame4 */

     jComboBox1.addItem("1");
     jComboBox1.addItem("2");
     jComboBox1.addItem("3");
     jComboBox1.addItem("4");
     jComboBox1.addItem("5");
     jComboBox1.addItem("6");
     jComboBox1.addItem("7");
     jComboBox1.addItem("8");
     jComboBox1.addItem("9");
     jComboBox1.addItem("10");
     jComboBox1.addItem("11");
     jComboBox1.addItem("12");
     jComboBox1.addItem("13");
     jComboBox1.addItem("14");
     jComboBox1.addItem("15");
     jComboBox1.addItem("16");
     jComboBox1.addItem("17");
     jComboBox1.addItem("18");
     jComboBox1.addItem("19");
     jComboBox1.addItem("20");
     jComboBox1.addItem("21");
     jComboBox1.addItem("22");
     jComboBox1.addItem("23");
     jComboBox1.addItem("24");
     jComboBox1.addItem("25");
     jComboBox1.addItem("26");
     jComboBox1.addItem("27");
     jComboBox1.addItem("28");
     jComboBox1.addItem("29");
     jComboBox1.addItem("30");
     jComboBox1.addItem("31");


     /* adding months in the jFrame4 */


     jComboBox2.addItem("Jan");
     jComboBox2.addItem("Feb");
     jComboBox2.addItem("Mar");
     jComboBox2.addItem("Apr");
     jComboBox2.addItem("May");
     jComboBox2.addItem("Jun");
     jComboBox2.addItem("Jul");
     jComboBox2.addItem("Aug");
     jComboBox2.addItem("Sep");
     jComboBox2.addItem("Oct");
     jComboBox2.addItem("Nov");
     jComboBox2.addItem("Dec");

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

           String user_name = jTextField1.getText();

           if ( user_name.isEmpty() ) {

             JOptionPane.showMessageDialog(rootPane, "You didn't type any username.");

           }

 else {
       
   
        jFrame1.dispose();
         jFrame2.setBounds(100, 100, 710, 500);
        jFrame2.setVisible(true);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


        /* getting the password from the password filed and alalyze the
         * password. If the password has a charater and it's 6 characters
         * long, then it's ok.
         */
        char[] text1 = jPasswordField1.getPassword();

        char[] text2 = jPasswordField2.getPassword();

      

        int i = 0;

        int count = 0;

        char temp;

        while ( i < text1.length ) {

            temp = text1[i];

            if ( isLetter(temp) == true ) {

                count++;
            }

            if ( text1[i] != text2[i] ) {
                       JOptionPane.showMessageDialog(rootPane, "Passwords do not match !");
                       break;
            }

            i++;
        
        }

        if(count == 0 || text1.length < 6) {

            JOptionPane.showMessageDialog(rootPane, "Password must contain a letter, and atleast one character. Please try again.");

        }

        else {

        jFrame2.dispose();
        jFrame3.setBounds(100, 100, 710, 500);
        jFrame3.setVisible(true);


        /* A XML class onject 'x' for access to the XML database.
         *
         * A encrypt_and_decrypt 'y' for decrypt and encrypt the XML
         *
         * database for using.
         */


        }

     

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

                jFrame3.dispose();
        jFrame4.setBounds(100, 100, 710, 500);
        jFrame4.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
                 // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        /* setting some if's for months. some has 30 days and
         * some has 31. Feb got 28.
         */

       String date = (String) jComboBox1.getSelectedItem();
       String month = (String) jComboBox2.getSelectedItem();

       String year = jTextField2.getText();
       System.out.println(year.length());
        System.out.println(year.charAt(0));


       if ( year.charAt(0) != '1' && year.charAt(0)!= '2'||  year.length() != 4 ) {

            JOptionPane.showMessageDialog(rootPane, "Wrong year." );

       }
   

        else if(date.equals("31")) {

           if ( month.equals("Sep") || month.equals("Apr") || month.equals("Jun") || month.equals("Nov") || month.equals("Feb") ) {

               JOptionPane.showMessageDialog(rootPane, "Wrong date." );
           }

        }

        else if(date.equals("30")) {

           if ( month.equals("Feb")) {

               JOptionPane.showMessageDialog(rootPane, "Wrong date." );
           }
       }



 else {

        jFrame4.dispose();
        jFrame5.setBounds(100, 100, 710, 500);
        jFrame5.setVisible(true);


 }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                    String sec_ques = jTextField3.getText();
            String sec_ans = jTextField4.getText();
            if ( sec_ques.isEmpty() || sec_ans.isEmpty() ) {
                JOptionPane.showMessageDialog(rootPane, "Empty ques/ans." );

                }

            else {

        jFrame5.dispose();
        jFrame6.setBounds(100, 100, 710, 500);
        jFrame6.setVisible(true);

        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
                System.out.println ("chekced")  ;      // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        /* adding all admin password to XML file.
         *
         * dont know if frame dispose will backfire upon me
         */

       String user_name = jTextField1.getText();
       System.out.println (user_name);
       char[] temp = jPasswordField1.getPassword();
       String user_pass = String.valueOf(temp); // thanks to http://www.artima.com/legacy/answers/Oct2001/messages/265.html
       String DATE_FORMAT_NOW = "yyyy-MM-dd HH:mm:ss";
       Calendar cal = Calendar.getInstance();
       SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_NOW);
       String creation_time = sdf.format(cal.getTime());
       String b_date = (String) jComboBox1.getSelectedItem();
       String b_month = (String) jComboBox2.getSelectedItem();
       String b_year =  jTextField2.getText();
       String sec_ques = jTextField3.getText();
       String sec_ans = jTextField4.getText();

       /* pretty disgusting stuff to convert
        * all boolean to string.huff
        */

       String add_clients;
       String edit_client_opt;
       String can_chat;
       String see_logs;
       String send_msg;
        String add_files;
        String set_file_profiles;
        String change_setting;

       if ( jCheckBox1.isSelected() == true ) {

            add_clients = "true";

        }

    else {

            add_clients = "false";
     }

    if ( jCheckBox2.isSelected() == true ) {

           edit_client_opt= "true";

        }

    else {

            edit_client_opt = "false";
    }


   if ( jCheckBox3.isSelected() == true ) {

            can_chat= "true";

        }

  else {

            can_chat = "false";
   }

     if ( jCheckBox4.isSelected() == true ) {

           see_logs= "true";

        }

     else {

           see_logs = "false";
    }



if ( jCheckBox5.isSelected() == true ) {

           send_msg = "true";

        }

 else {

            send_msg  = "false";
 }


if ( jCheckBox6.isSelected() == true ) {

           add_files = "true";
        }

 else {

           add_files   = "false";
 }


if ( jCheckBox7.isSelected() == true ) {

           set_file_profiles = "true";
        }

 else {

          set_file_profiles   = "false";
 }

if ( jCheckBox8.isSelected() == true ) {

           change_setting = "true";
        }

 else {

           change_setting   = "false";
 }





         XML x = new XML();
        encrypt_and_decrypt y = new encrypt_and_decrypt();
        try {
            y.decrypt("dbase.rtft", "dbase.xml");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            x.add_element("dbase.xml", "user_info");
            x.add_sub_element("dbase.xml", "user_info", user_name, user_name);
            x.add_element("dbase.xml", "user_settings");
            x.add_element("dbase.xml", "first_run");
            x.add_sub_element("dbase.xml", "first_run", "run_once", "false");


        } catch (ParserConfigurationException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerConfigurationException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

               x.modify_sub_element("dbase.xml","first_run", "run_once", "false");
               x.add_sub_element("dbase.xml", user_name, "user_pass", user_pass);
               x.add_sub_element("dbase.xml",  user_name, "creation_time", creation_time);
                x.add_sub_element("dbase.xml", user_name, "b_date", b_date);
                 x.add_sub_element("dbase.xml", user_name, "b_month", b_month);
                  x.add_sub_element("dbase.xml", user_name, "b_year", b_year);
                   x.add_sub_element("dbase.xml", user_name, "sec_ques", sec_ques);
                    x.add_sub_element("dbase.xml", user_name, "sec_ans", sec_ans);
                     x.add_sub_element("dbase.xml", user_name, "acc_type", "admin");
                     x.add_sub_element("dbase.xml", user_name, "first_time", "false");
                     x.add_sub_element("dbase.xml", "user_settings", "add_clients", add_clients);
                      x.add_sub_element("dbase.xml", "user_settings", "edit_client_opt", edit_client_opt);
                      x.add_sub_element("dbase.xml", "user_settings", "can_chat", can_chat);
                      x.add_sub_element("dbase.xml", "user_settings", "see_logs", see_logs);
                      x.add_sub_element("dbase.xml", "user_settings", "see_logs", see_logs);
                       x.add_sub_element("dbase.xml", "user_settings", "send_msg", send_msg);
                        x.add_sub_element("dbase.xml", "user_settings", "add_files", add_files);
                         x.add_sub_element("dbase.xml", "user_settings", "set_file_profiles", set_file_profiles);
                         x.add_sub_element("dbase.xml", "user_settings", "change_setting", change_setting);

 
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerConfigurationException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        }
        



         try {
           y.encrypt("dbase.xml", "dbase.rtft");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(server_wizard.class.getName()).log(Level.SEVERE, null, ex);
        }

        core_main_temp z = new core_main_temp();
       z.setBounds(100,100,730,430);
       z.setVisible(true);
       setVisible(false);


        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed


             jFrame6.dispose();
        jFrame7.setBounds(100, 100, 710, 500);
        jFrame7.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed


                jFrame7.dispose();
        jFrame8.setBounds(100, 100, 710, 500);
        jFrame8.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
    * @param args the command line arguments
    */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new server_wizard().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JFrame jFrame6;
    private javax.swing.JFrame jFrame7;
    private javax.swing.JFrame jFrame8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
